
development:
  adapter:  mysql2
  host:     127.0.0.1
  encoding: utf8
  database: sample_app
  pool:     5
  username: root
  password: tienbuiEPU2992
  reconnect: false

# test:
#   adapter:  mysql2
#   host:     127.0.0.1
#   encoding: utf8
#   database: DesignTropic_test
#   pool:     5
#   username: root
#   password:
#   reconnect: false

# production:
#   adapter:  mysql2
#   host:     127.0.0.1
#   encoding: utf8
#   database: DesignTropic_production
#   pool:     5
#   username: root
#   password:
#   reconnect: false 