# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a998876a4ad9e0b175abba880486bc04900e18e4c2c6b2c2705bad6fd9c9c416affc1b9c574e96f38aa11b537cefb4f63509e7d0096bf604cb23c93047dd0175

test:
  secret_key_base: 6613c6445f26ed28f8d549d25ab002b7fe0325636e4eef25049e4e1c4296dd2d99ff3df4f833901d53c1e99c046d7a71892b7c8e96da4caacfdfd18de2400586

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
